### ISSUE TITLE
No longer works with latest Combres 2.2.2.15

### ISSUE THREAD

**Issue by danspam** [pauldotknopf/Adept.Combres#1]
It seems that the latest version of combres (2.2.2.15) uses a newer version of dotless.Core (1.3.1) and this causes the following exception:

Method 'GetBinaryFileContents' in type 'AdeptFileReader' from assembly 'Adept.Combres, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

The IFileReader interface that AdeptFileReader implements has a different signature in dotless.Core 1.3.1

**Comment by pauldotknopf** [comment]
Thanks! I'm on my way to work now. I will post a fix later this evening and deploy it to NuGet.

**Comment by pauldotknopf** [comment]
Committed and published a new NuGet package.

https://github.com/theonlylawislove/Adept.Combres/commit/f76f55b71b6e052118df9de4e3eb1c96cea87a0e
